# Generated by Django 6.0.2 on 2026-02-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField()),
                ('average_risk', models.FloatField()),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
