# Generated by Django 6.0.2 on 2026-02-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentanalysis',
            options={},
        ),
    ]
